### ISSUE TITLE
Include QR-Code reader

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#390] opened 2021-03-14 21:11 UTC
https://dev.to/rafael_winter/barras-a-simple-barcode-qr-code-reader-package-for-flutter-2mof

https://github.com/deadblit/barras

**Comment by S-Man42** [comment] 2021-04-10 09:44
That's not gonna happen in near future.

The Problem: It requires access to the camera. I by myself, I am very critical to all apps which requires camera or microphone permissions without any obvious reason. The problem is, that the requirement for reading a QR code (importing formulas from other devices) is too tiny compared with the rest of the entire app. That's a feature, only a extreme minority knows about. And this minority knows how to use an external QR reader app. 

Therefore, I don't need to take the risk that a user doesn't install the app because he sees "Requires Permission for Camera" (which is, of course, somewhat irritating, we would implement this only with an explicit permission dialogue, but the PlayStore and AppStore listing state this nonetheless). 

Maybe someone we have a broader requirement for a camera usage and then, naturally, the first feature which will be integrated, will be the QR reader.

**Closed by S-Man42** 2021-04-10 09:44 UTC
Labels: enhancement, feature
