### ISSUE TITLE
Show hidden image data

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#524] opened 2021-05-03 16:50 UTC
recognize hidden information from a picture 
jpg -> rar -> hiden file
example
http://coord.info/GC6A81J
http://coord.info/GC6NF76
http://coord.info/GC4TX8W

**Comment by S-Man42** [comment] 2021-05-11 04:23
Duplicate of #412

**Comment by S-Man42** [comment] 2021-07-29 09:27
Ok, tried following without success:

http://coord.info/GC3BPHA

Here you get the background image: http://mroann.de/GC3BPHA/bg.jpg (JPG: Contains MP3 file, which can be extracted as well, contains a TXT)

http://coord.info/GC4AZHP -> http://bnbcaching.com/caches/gc4azhp/robot2.jpg contains text file

**Comment by S-Man42** [comment] 2021-07-29 09:32
I had no success with the current EXIF tool and also not using the "archive plugin directly":
```

   try {
      var archive = ZipDecoder().decodeBytes(file.bytes);

      print('EXTRACTED ZIP');
      print(archive.length);
    }catch(e){}

    try {
      var archive2 = BZip2Decoder().decodeBytes(file.bytes);

      print('EXTRACTED BZIP2');
      print(archive2.length);
    }catch(e){print('TRIED BZIP2');}

    try {
      var archive3 = GZipDecoder().decodeBytes(file.bytes);

      print('EXTRACTED GZIP');
      print(archive3.length);
    }catch(e){print('TRIED GZIP');}

    try {
      var archive4 = TarDecoder().decodeBytes(file.bytes);

      print('EXTRACTED TAR');
      print(archive4.length);
    }catch(e){print('TRIED TAR');}

    try {
      var archive5 = ZLibDecoder().decodeBytes(file.bytes);

      print('EXTRACTED ZLIB');
      print(archive5.length);
    }catch(e){print('TRIED ZLIB');}
```

which yields (for robot2.jpg):

```
I/flutter ( 5487): EXTRACTED ZIP
I/flutter ( 5487): 0
I/flutter ( 5487): TRIED BZIP2
I/flutter ( 5487): TRIED GZIP
I/flutter ( 5487): TRIED TAR
I/flutter ( 5487): TRIED ZLIB
```

Any ideas?

**Comment by S-Man42** [comment] 2021-07-29 09:38
The bg.jpg seems to be a TAR. Output is:

```
I/flutter ( 5487): EXTRACTED ZIP
I/flutter ( 5487): 0
I/flutter ( 5487): TRIED BZIP2
I/flutter ( 5487): TRIED GZIP
I/flutter ( 5487): EXTRACTED TAR
I/flutter ( 5487): 4
I/flutter ( 5487): TRIED ZLIB
```
which means: Was able to extract as TAR an found 4 files.

But when I try to display the file names:

```
     for (final packedfile in archive4) {
        final filename = packedfile.name;
        if (packedfile.isFile) {
          // final data = packedfile.content as List<int>;
          print(packedfile.name);
        } else {
          // Directory('out/' + filename)
          //   ..create(recursive: true);
        }
      }
```

it returns only bullshit :( Maybe I am doing something wrong...

```
I/flutter ( 5487): ÿØÿà
I/flutter ( 5487):
I/flutter ( 5487): YêîWóâ?*¤ªóÔ`´®Ó¶Op|S½¦bÖè<>**EÎÓ@æ~å:Ra
I/flutter ( 5487): ã¼Ý(@ÊÈe6ØçþñÓáù©ÎÆiÝÜþhø~òáKhsÌCGÒ?ùBÉ²Þ 4_s5Æ»ù³'÷¡ù~ò0Yé¤%'6½á±º Þn¨×
```

**Comment by S-Man42** [comment] 2021-07-29 10:01
https://github.com/brendan-duncan/archive/issues/156

**Closed** 2021-08-02 14:54 UTC

**Comment by S-Man42** [comment] 2021-08-24 12:23
http://coord.info/GC6A81J -> Problem with extracting. Error on reading ArchiveFile.content
http://coord.info/GC6NF76 -> Works great. Even with saving nested GPX file and open it in Map Tool :)
http://coord.info/GC4TX8W -> Not quite clear, where the hidden data should be... Even Saarfuchs Mystery Wizard does not find some...

**Comment by Mike-3** [comment] 2021-08-24 12:35
http://coord.info/GC6A81J
Is a rar archive. We have no extract tool at the moment.
File names are possibile.
http://coord.info/GC4TX8W
Missing original link from the image.
(http://www.linkfile.de/download-bd11474c79e4222d48e8c1521f8d4e3b.php), from c:geo backup. Is death link.
