### ISSUE TITLE
Formula Resolver / WebSite

### ISSUE THREAD

**Issue by mahoplus** [S-Man42/GCWizard#129] opened 2020-07-05 15:34 UTC
to add a new formula group doesn't work - to click on the plus-sign results no action

**Comment by capoaira** [comment] 2020-07-05 15:55
Yes, the Formula Solver does not work in the web view: #37 
If you download the app from the google play store or from the apple app store, the Formula Solver will work.

**Comment by mahoplus** [comment] 2020-07-05 16:06
ok, thanks for the advice. I use the solver under android and it works well, but editing complicated formula is not confortable on a mobile device

**Comment by S-Man42** [comment] 2020-07-05 16:20
Hi,

currently I am working on this. This demands a complete internal rebuild of the formula solver, but the goal is to get it worked at the web view. Then it will be also possible to export/import the formulas.

#37 #106

**Comment by S-Man42** [comment] 2020-07-15 11:29
Duplicate of #37

**Closed by S-Man42** 2020-07-15 11:29 UTC
